// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AAvatar: typeof import('ant-design-vue/es')['Avatar']
    AButton: typeof import('ant-design-vue/es')['Button']
    ACard: typeof import('ant-design-vue/es')['Card']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    AResult: typeof import('ant-design-vue/es')['Result']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
  }
}

export { }
